### ISSUE TITLE
Package does not build without XDG export

### ISSUE THREAD

**Issue by ivanvmel** [ccozianu/XTestAWSBeanStalkWithMaven#1]
[INFO] Surefire report directory: /Users/ivm/Desktop/CostinProject/XTestAWSBeanStalkWithMaven/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running me.mywiki.sample2.tests.TestJsonDependencies
Successfully parsed: {"ala":"bala","protocala":true,"x":[0,1,2,3]}
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.46 sec <<< FAILURE!
canReadUserProfile(me.mywiki.sample2.tests.TestJsonDependencies)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:894)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:879)
	at me.mywiki.sample2.tests.TestJsonDependencies.canReadUserProfile(TestJsonDependencies.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Tests in error: 
  canReadUserProfile(me.mywiki.sample2.tests.TestJsonDependencies)

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] -------------------------------------------------

**Comment by ccozianu** [comment]
Fixed in ccozianu_wip branch, it wasn't an issue of XDG_CONFIG_HOME, but of maven conventions.

TODO: create a roadmap issue
